# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalAndPushNotification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end
